#!/bin/sh
# File generated by ocamlbuild

cd /home/ashish/work/purdue/code/git/catalyst/ocaml-catalyst/ocaml-frontend-4.03/parsing

rm -f readfile.cmi
rm -f readfile.cmo
# Also clean the script itself
rm -f /home/ashish/work/purdue/code/git/catalyst/ocaml-catalyst/ocaml-frontend-4.03/parsing/_build/sanitize.sh
