#!/bin/sh
# File generated by ocamlbuild

cd /home/ashish/work/purdue/code/git/catalyst/ocaml-catalyst/ocaml-frontend-4.03/tests

rm -f test3.cmi
rm -f test3.cmo
rm -f test4.cmi
rm -f test4.cmo
# Also clean the script itself
rm -f /home/ashish/work/purdue/code/git/catalyst/ocaml-catalyst/ocaml-frontend-4.03/tests/_build/sanitize.sh
